tunnel: c0db2e38-0ce2-495b-86a5-c9c39287e6e8
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: nas.soundsgoodlab.sg
    service: http://nextcloud:80
    originRequest:
      noTLSVerify: true
      disableChunkedEncoding: true
      connectTimeout: 60s
      tlsTimeout: 60s
      keepAliveTimeout: 90s
      keepAliveConnections: 100
  - service: http_status:404

loglevel: info
metrics: 0.0.0.0:8080
